version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_wallet
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - wallet_data:/var/lib/postgresql/data

  wallet-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

volumes:
  wallet_data: